spring:
  application:
    name: App2
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver

server:
  port: ${HTTP_PORT:8082}

grpc:
  port: ${GRPC_PORT:9092}